esphome:
  name: varmeovn
  platform: ESP8266
  board: d1_mini
  includes:
    - mill.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Varmeovn Fallback Hotspot"
    password: "Set your own PWD"

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
# Enable Home Assistant API
api:
  password: !secret HA_API
  encryption:
    key: " "  //KEY randomly-generated base64 key
ota:
  password: !secret HA_API

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new MyCustomClimate();
    App.register_component(my_custom_climate);
    return {my_custom_climate};
  

  climates:
    - name: "Soverom"
      id: heater
      visual:
         min_temperature: 5 °C
         max_temperature: 30 °C
         temperature_step: 1 °C
         

sensor:
  - platform: total_daily_energy // Resetter
    name: "Total Daily Energy"
    power_id: my_power
    device_class: "energy"
    state_class: "total_increasing"
    
  - platform: template
    name: "heater Power"
    id: my_power
    lambda: |-
      if (id(heater).action ==  CLIMATE_ACTION_HEATING) {
        return 900.0;   // ovnes effekt i Watt
      } else {
        return 0.0;
      }
    filters:
      - multiply: 0.001
    unit_of_measurement: kW
    update_interval: 60s
    
# Enable time component to reset energy at midnight
time:
  - platform: sntp
    id: my_time
