#Remember to change the value for consupmtion (watt) on line XX to the value of your heater. 
substitutions:
  devicename: "heater"  #Lower case name
  upper_devicename: Heater

esphome:
  name: $devicename
  
esp8266:
  board: d1_mini
  
external_components:
  - source:
      type: local
      path: components
    components:
      - mill

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret fallback_wifi_pw

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
# Enable Home Assistant API
api:
  password: !secret HA_API
  encryption:
    key: !secret Secret_KEY
ota:
  - platform: esphome
    password: !secret HA_API

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new MyCustomClimate();
    App.register_component(my_custom_climate);
    return {my_custom_climate};
  
  climates:
    - name: "${devicename} Climate"
      id: heater
      visual:
         min_temperature: 5 °C
         max_temperature: 30 °C
         temperature_step: 1 °C
         
sensor:
  - platform: total_daily_energy
    name: ${devicename} Total Daily Energy
    power_id: ${devicename}
    device_class: "energy"
    state_class: "total_increasing"
    
  - platform: template
    name: "${devicename} Power"
    id: ${devicename}
    lambda: |-
      if (id(heater).action ==  CLIMATE_ACTION_HEATING) {
        return 900.0;
      } else {
        return 0.0;
      }
    filters:
      - multiply: 1
    unit_of_measurement: W
    update_interval: 60s
    
# Enable time component to reset energy at midnight
time:
  - platform: sntp
    id: my_time
