#Remember to change the value for consupmtion (watt) on line 66 to the value of your heater. 
substitutions:
  devicename: "navn"
  upper_devicename: "NAVN"
  
esphome:
  name: $devicename
  
esp8266:
  board: d1_mini
  
external_components:
  - source:
      type: git
      url: https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater
    components: [mill]
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret fallback_wifi_pw

captive_portal:

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0
# Enable Home Assistant API
api:
  encryption:
    key: !secret Secret_KEY
ota:
  - platform: esphome
    password: !secret HA_API
    
climate:
  - platform: mill
    name: ${devicename} Heater
    id: heater
    uart_id: uart_bus

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

sensor:
  - platform: total_daily_energy
    name: ${devicename} Daglig forbruk
    power_id: heater_power
    device_class: "energy"
    state_class: "total_increasing"

  - platform: template
    name: ${devicename} effekt
    id: heater_power
    lambda: |-
      if (id(heater).action == CLIMATE_ACTION_HEATING) {
        return 900.0;
      } else {
        return 0.0;
      }
    unit_of_measurement: W
    update_interval: 60s

time:
  - platform: sntp
    id: my_time
